Fix flake8-bugbear warning
B009 Do not call `getattr` with a constant attribute value.
     It is not any safer than normal property access.

Fix a MyPy typing issue, instead of using a Python hack to
silence the PyPy error:
	error: Incompatible types in assignment (expression
	       has type "Optional[str]", variable has type
	       "str")  [assignment]